feat: UTH-25 - add typeCode to ApartmentInfo
Bostads-AB-Mimer/onecore-types pull request #127
Opened 2024-11-11 14:55 UTC by momentiris

2024-11-12 15:30 UTC, mittistormen requested changes

2024-11-12 15:30 UTC, mittistormen commented on src/types.ts
> +  typeCode: string
Jag tycker typeCode är lite för generiskt för att beskriva detta. Kan den få ett tydligare namn så att man förstår att det handlar om antal rum (för det är det väl)?

2024-11-13 07:59 UTC, momentiris commented on src/types.ts
> +  typeCode: string
Ja vi kan ha något annat namn. Jag satte bara något som kändes rimligt utifrån den mappning som redan finns och vad tabellerna verkar kallas. 

Har du något förslag?

2024-11-13 08:59 UTC, mittistormen commented on src/types.ts
> +  typeCode: string
Japp fattar! Jag tänker bara att tabellerna inte är så väl namngivna från början och att det nog ställer till problem för oss framöver

Kanske kan den heta ngt med roomCount?

2024-11-13 09:14 UTC, mittistormen approved these changes

2024-11-13 09:16 UTC, merged